# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'TopPlaces'
  app.identifier = "com.flophouse.cs193p.#{app.name}"
  app.vendor_project('vendor', :static)
  app.device_family = [:iphone]
end
